Make benchmark use datasets in the cluster 🥡
Otherwise every benchmark we need to copy 200MB of data

diff --git a/.github/workflows/benchmark.yaml b/.github/workflows/benchmark.yaml
--- a/.github/workflows/benchmark.yaml
+++ b/.github/workflows/benchmark.yaml
@@ -61,19 +61,33 @@ jobs:
           JOB_TAG="${PETNAME}_${DATE_NOW}"
           UNITN_BASE=$(echo "${{secrets.UNITN_USERNAME}}" | sed 's/@unitn.it//')
           BASE_DIR=/home/${UNITN_BASE}/HPC_course/benchmarks/$JOB_TAG
+          DATA_DIR=/home/${UNITN_BASE}/HPC_course/data
           CODE_DIR=$BASE_DIR/code_to_compile
           RUN_DIR=$BASE_DIR/runs
 
-          rm -rf ./unitn_vpn_script.sh ./unitn_hireport.sh
+          echo "Checking that the data directory exists on the cluster"
           sshpass -e \
             ssh -l "${{secrets.UNITN_USERNAME}}" hpc2.unitn.it \
-              "rm -rf $CODE_DIR
+              "if [[ ! -d $DATA_DIR ]]; then
+                 echo "It seems that the dataset directory is missing on the cluster. Exiting"
+                 exit 1
+               fi
+              "
+
+          echo "Removing files we do not need to copy on the cluster"
+          rm -rf ./unitn_vpn_script.sh ./unitn_hireport.sh ./data
+
+          echo "Ensuring the directories we need on the cluster are there (and clean)"
+          sshpass -e \
+            ssh -l "${{secrets.UNITN_USERNAME}}" hpc2.unitn.it \
+              "rm -rf $CODE_DIR $RUN_DIR
                for i in {1..10}; do
                  mkdir -p $CODE_DIR
                  mkdir -p $RUN_DIR
                done;
               "
 
+          echo "Populating benchmark info file"
           RUN_TRIGGER_FILE=./scripts/CI/run_trigger
           echo "JOB_TAG=$JOB_TAG" > $RUN_TRIGGER_FILE
           echo "Github commit hash=${{GITHUB.SHA}}" >> $RUN_TRIGGER_FILE
@@ -83,11 +97,13 @@ jobs:
           sed -i "s/{{RESULTS_GOOGLE_FORM_ID}}/${{secrets.RESULTS_GOOGLE_FORM_ID}}/g" ./scripts/CI/benchmark.sh 
           sed -i "s/{{UNITN_BASE}}/$UNITN_BASE/g" ./scripts/CI/benchmark.sh 
 
+          echo "Copying the code to the cluster"
           sshpass -e \
             scp -r -o "user=${{secrets.UNITN_USERNAME}}" . "hpc2.unitn.it:$CODE_DIR"
 
           echo "BASE_DIR=$BASE_DIR" >> $GITHUB_OUTPUT
           echo "CODE_DIR=$CODE_DIR" >> $GITHUB_OUTPUT
+          echo "DATA_DIR=$DATA_DIR" >> $GITHUB_OUTPUT
       - name: Compile the code
         env:
           SSHPASS: ${{secrets.UNITN_PASSWORD}}
@@ -122,7 +138,8 @@ jobs:
                # Have to put it in background AND redirect outputs,
                # else GitHub will not consider this step finished
                # until the benchmark script has finished too.
-               nohup ./benchmark.sh 1>'./benchmark_stdout.log' 2>'./benchmark_stderr.log' &
+               nohup ./benchmark.sh ${{steps.copy_to_cluster.outputs.DATA_DIR}} \
+                 1>'./benchmark_stdout.log' 2>'./benchmark_stderr.log' &
                disown
                echo 'Benchmarking launched 🚀'
               "
